library('randomForest')

# Random Forest Object is generated by the 'randomForest' command.
# mtry is the number of variables tested for each split, ntree is the
# number of trees grown, xtest and ytest specify respectively the 
# set of predictors to test the data on, and the set of correct responces
# corresponding with the predictors.  

fold.rf <- randomForest(edibility~., data=folds[[1]], mtry=10, ntree=250,
			xtest=folds[[2]][-1], ytest=folds[[2]]$edibility,importance=TRUE, proximity=TRUE)

print(fold.rf)

## Look at variable importance:
round(importance(fold.rf), 2)


# Here is a data visualization method I found for the random forest,
# I'm not sure what it means exactly, but it looks nice.  

fold.mds <- cmdscale(1 - fold.rf$proximity, eig=TRUE)
op <- par(pty="s")
pairs(cbind(folds[[1]][,2:23], fold.mds$points), cex=0.6, gap=0,
col=c("green", "blue")[as.numeric(folds[[1]]$edibility)],
main="Mushroom Data: Predictors and MDS of Proximity Based on RandomForest")
par(op)
print(fold.mds$GOF)

