library('randomForest')
library('plyr')



##					FUNCTIONS					##

# This function applies round and mean functions at the 
# same time so that both operations can be completed using
# a single 'apply' call.
round_mean <- function(x, digits)
{
	round(mean(x), digits)
}

# Function to generate an RF model given a data frame object from the 
# mushrooms data set, and some test data.
grow_forest <- function(data_frame, test_data) {

# Random Forest Object is generated by the 'randomForest' command.
# mtry is the number of variables tested for each split, ntree is the
# number of trees grown, xtest and ytest specify respectively the 
# set of predictors to test the data on, and the set of correct responces
# corresponding with the predictors.  
	randomForest(edibility~., data=data_frame, mtry=10, ntree=500,
			xtest=test_data[-1], ytest=test_data$edibility,
			importance=TRUE, proximity=TRUE)
}


# A function to slightly reduce the amount of code required
# to print a summary.
print_summary <- function(item) {
	print(summary(item))
}


# A function to extract the confusion matrices from the random
# forest object returned by randomforest.
get_conf_matrix <- function(rf_object) {
	rf_object$confusion
}

# A function to write a confusion matrix to the results file.
write_confusion_matrix <- function(c_matrix, r_file, iteration)
{
	write(paste("Iteration", iteration, sep=" ", collapse=NULL), 
							file=r_file, ncolumns=1, append=TRUE)
	write(c_matrix[1:2,], file=r_file, ncolumns=2, append=TRUE)
}


###					MAIN PROGRAM					###

			##		Variables 		##

results_file='results_temp/rand_forest_results.txt'

# This matrix will hold the final results after running the complete
# cross validation.
confusion_matrix_averages <- vector("list", (length(folds)-1))




			## 		Logic		##
			
	# Begin results file.
write("\t\tBEGIN RANDOM FOREST RESULTS\n", file=results_file,
	  ncolumns = 1, append=FALSE)
			
			
# In this section of the code, the goal is to cross-validate over each
# of the folds.  So for i in nFolds, it will make the i'th fold the
# testing data, and it will build a tree from each of the remaining 
# folds.  Then it will test the fit of each tree on the test fold.  
#
# The results of each test are added to a list, and finally at the 
# end all the average test perfomance is calculated and reported.  
for( i in 1:(length(folds)))
{
	# Name i'th fold 'test' and add the 
	# remaining folds to a list called 'train'
	test  <- folds[[i]]
	train <- folds[c(seq(1:(length(folds))))[-i]]
 
	
			
	# First generate the models for each of the training data lists.
	fits  <- lapply(train, FUN=grow_forest, test_data=test)

	# Generate a list of confusion matrices.
	conf_mats <- lapply(fits, FUN=get_conf_matrix)
	
	# Add the average confusion matrix for this iteration to the 
	# confusion_matrix_averages list.
	confusion_matrix_averages[[i]]<- apply(simplify2array(conf_mats),
			c(1,2), mean)
	
	# Round the matrix prior to printing.
	lapply(conf_mats, FUN=round_mean, digits=1)
	
	# Print the confusion matrices to the file.
	lapply(conf_mats, FUN=write_confusion_matrix, r_file=results_file, iteration=i)
			
 }
 
# Write the average confusion matrices to the results file.
lapply(confusion_matrix_averages, FUN=write_confusion_matrix, r_file=results_file, iteration="Averages")
 
# Finally, generate a single confusion matrix from all the average 
# confusion matrices and print it to the screen.
final_confusion_matrix <- apply(simplify2array(confusion_matrix_averages),
						  c(1,2), ceil_mean)
write(final_confusion_matrix, file=results_file, ncolumns=2, append=TRUE)
print(final_confusion_matrix)
